services:
  prepare-data:
    image: debian:bookworm-slim
    volumes:
      - ./preparePermission.sh:/preparePermission.sh
      - ./data:/data
    working_dir: /
    entrypoint: ["/bin/sh", "-c", "chmod +x ./preparePermission.sh && ./preparePermission.sh"]

  plants-measurements:
    build: ./apps/sensor
    environment:
      DIRECTUS_URL: "http://rocket-meals-directus:8055"
      DIRECTUS_COLLECTION: "plants_measured_values"
      SENSOR_DEBUG: "false"
    depends_on:
      rocket-meals-directus:
        condition: service_started
    restart: always
    networks:
      - directus_network
    devices:
      - /dev/i2c-1:/dev/i2c-1

  traefik:
    extends:
      service: traefik
      file: apps/proxy/docker-compose.yaml

  rocket-meals-directus:
    depends_on:
      prepare-data:
        condition: service_completed_successfully
      rocket-meals-database:
        condition: service_healthy
      rocket-meals-cache:
        condition: service_started
    extends:
      service: rocket-meals-directus
      file: apps/backend/docker-compose.yaml

  rocket-meals-database:
    depends_on:
      prepare-data:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus"]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      service: rocket-meals-database
      file: apps/backend/docker-compose.yaml

  rocket-meals-cache:
    extends:
      service: rocket-meals-cache
      file: apps/backend/docker-compose.yaml
    networks:
      - directus_network

networks:
  directus_network: {}
  traefik:
    driver: bridge
    name: traefik
