x-plants-measurements-base: &plants-measurements-base
  build: ./apps/sensor
  env_file:
    - .env
  environment:
    DIRECTUS_URL: "http://flower-pi-directus:8055"
    DIRECTUS_COLLECTION: "sensor_measurements"
    SENSOR_DEBUG: "${SENSOR_DEBUG:-false}"
    ADMIN_EMAIL: "${ADMIN_EMAIL:-}"
    ADMIN_PASSWORD: "${ADMIN_PASSWORD:-}"
  depends_on:
    flower-pi-directus:
      condition: service_started
  restart: always
  networks:
    - directus_network

services:
  prepare-data:
    image: debian:bookworm-slim
    volumes:
      - ./preparePermission.sh:/preparePermission.sh
      - ./data:/data
      - ./.env:/data/.env
    working_dir: /
    entrypoint: ["/bin/sh", "-c", "chmod +x ./preparePermission.sh && ./preparePermission.sh"]

  plants-measurements:
    <<: *plants-measurements-base

  plants-measurements-hw:
    <<: *plants-measurements-base
    profiles:
      - sensor-hw
    devices:
      - /dev/i2c-1:/dev/i2c-1

  traefik:
    extends:
      service: traefik
      file: apps/proxy/docker-compose.yaml
    depends_on:
      prepare-data:
        condition: service_completed_successfully

  flower-pi-directus:
    depends_on:
      prepare-data:
        condition: service_completed_successfully
      flower-pi-cache:
        condition: service_started
    extends:
      service: flower-pi-directus
      file: apps/backend/docker-compose.yaml

  flower-pi-database-sync:
    env_file:
      - .env
    depends_on:
      prepare-data:
        condition: service_completed_successfully
    extends:
      service: flower-pi-database-sync
      file: apps/backend/docker-compose.yaml

  flower-pi-cache:
    extends:
      service: flower-pi-cache
      file: apps/backend/docker-compose.yaml
    networks:
      - directus_network

networks:
  directus_network: {}
  traefik:
    driver: bridge
    name: traefik
